# constantes globales

W_DAMAGE = 1.0
W_BLOCK = 0.9
W_DRAW = 1.5
W_COST = 1.2
W_EXHAUST = 0.2
W_SELF_DAMAGE = -1.5
W_ENERGY_GAIN = 2.0
W_COST_REDUCTION = 1.0
W_VULNERABILITY = 0.5
W_WEAKNESS = 0.5
W_STRENGTH = 0.5
W_FRAILTY = 0.7
W_DMG_ALL = 0.3
W_STRENGTH_SCALING = 0.5
W_BLOCK_IF_ENEMY_ATTACKS = 0.3